version: '3'
services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: dockerfile.flask
    volumes:
      - "./:/app"
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - flask